### ISSUE TITLE
Discover HTTP Clients

### ISSUE THREAD

**Issue by Stadly** [http-interop/http-factory-discovery#6]
I realize that this is a library for discovering HTTP Factories (PSR-17), but have you considered also supporting discovering HTTP Clients (PSR-18)?

**Comment by shadowhand** [comment]
I'm not opposed to including it. However, that gets squarely into [httplug](http://httplug.io/) territory.

**Comment by Stadly** [comment]
Yes, that's true. [HTTPlug Discovery](https://github.com/php-http/discovery) currently doesn't support PSR-17. That means that two libraries are needed for discovery. Supporting both PSR-17 and SPR-18 in one library would be nice :)

**Comment by shadowhand** [comment]
HTTPlug discovery is much more advanced than this approach though. I don't know that there is really a significant performance difference though.

**Comment by shadowhand** [comment]
Fixed by #9.

**Comment by shadowhand** [comment]
@Stadly before I close this, can you please update the README to show usage of HTTP Client discovery? Thanks.

**Comment by Stadly** [comment]
Done: https://github.com/http-interop/http-factory-discovery/pull/10
